/**
    @file noobapluginsapi.h
    @author  Asitha Nanayakkara <daun07@gmail.com>

    @section LICENSE
    Nooba Plugin API source file
    Copyright (C) 2013 Developed by Team Nooba

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef NOOBA_H
#define NOOBA_H

//Qt
#include <QMetaType>

//! \brief Nooba namespace
/*!
 *  This namespace contains the identifiers used by the NoobaPluginAPI. Different enum types used
 */
namespace nooba {

    //! \brief Parameter type enum
    /*! Parameter types used in Nooba VSS system is defined here.
     */
    enum ParamType {
        IntParam        = 0, /*!<Integer parameter */
        DoubleParam     = 1, /*!<Double parameter to be used in parameters that need double precision */
        StringParam     = 2, /*!<To take string variables as input */
        RangeParam      = 3, /*!<Integer parameter */
        RegionParam     = 4, /*!<Parameter defining Region of Interest*/
        MultiValueParam = 5, /*!<Parameter where multiple predefined values are given to user to choose from*/
        FilePathParam   = 6  /*!<File paths are taken as input through this parameters*/
    };

    //! \brief The VideoState enum
    /*! This enum defines the current video state of the system.
     * Whether the video stream is playing, paused or stopped.
     */
    enum VideoState {
        PlayingState    = 0, /*!<video playing State*/
        PausedState     = 1, /*!<Video paused State*/
        StoppedState    = 2  /*!<video stopped State*/
    };

    //! \brief The AlertType enum
    /*! These are the type of alert levels identified by the system. These alert level
     *  can be generated by calling NoobaPluginAPI::generateAlert(...) function
     *  \sa NoobaPluginAPI::generateAlert()
     */
    enum AlertType {
        RedAlert    = 0, /*!<Highest priority alert, alert level 0*/
        AmberAlert  = 1  /*!<Secenod most important alert, alert level 1*/
    };

    //! \brief The PathType enum
    /*! In some cases different types of paths need to be selected. This enum difines the
     *  supported path types by the system
     */
    enum PathType {
        FilePath    = 0, /*!<Single file path */
        DirPath     = 1  /*!<Single Directory path */
    };
}

Q_DECLARE_METATYPE(nooba::ParamType)   // now ParamTypes can be used with QVariants
Q_DECLARE_METATYPE(nooba::VideoState)
Q_DECLARE_METATYPE(nooba::AlertType)
Q_DECLARE_METATYPE(nooba::PathType)

#endif // NOOBA_H
