#ifndef NOOBAPLUGINAPI_GLOBAL_H
#define NOOBAPLUGINAPI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NOOBAPLUGINAPI_LIBRARY)
#  define NOOBAPLUGINAPISHARED_EXPORT Q_DECL_EXPORT
#else
#  define NOOBAPLUGINAPISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NOOBAPLUGINAPI_GLOBAL_H
